apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: {{ .Operator.Plan.Name }}-job
spec:
  template:
    metadata:
      name: {{ .Operator.Plan.Name }}-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: bb
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "mysqldump -u root -h {{ .Instance.Name }}-mysql -p{{ .Params.password }} kudo > /backups/{{ .Params.backupFile }}"
        volumeMounts:
        - name: backup-pv
          mountPath: /backups
      volumes:
      - name: backup-pv
        persistentVolumeClaim:
          claimName: {{ .Instance }}-backup-pv